# cluster_config.yml - cluster configuration
__default__:
    account: sansam-lab
    partition: serial  # Default partition for CPU-only jobs
    cpus-per-task: 4
    mem: 16GB
    output: results/logs/slurm-%x.%A.%a.log
    gres: ""
    constraint: ""
Dorado_baseCalling_alignment:
    partition: gpu
    # constrain based on the availability of suitable gpus (ie l40s or a100)
    gres: "gpu:1"
    constraint: "l40s|a100"
    cpus-per-task: 6
    mem: 32GB
make_genome_index:
    partition: serial  # Run on normal CPU nodes
    cpus-per-task: 8
    mem: 16GB
demux_alignments:
    cpus-per-task: 24
split_bams:
    cpus-per-task: 12
dnascent_index:
    cpus-per-task: 4
    partition: gpu
    gres: "gpu:1"
    constraint: "l40s|a100"
dnascent_detect:
    partition: gpu
    gres: "gpu:1"
    constraint: "l40s|a100"
    cpus-per-task: 12
    mem: 16GB
dnascent_forksense:
    partition: gpu
    gres: "gpu:1"
    constraint: "l40s|a100"
    cpus-per-task: 12
    mem: 16GB
sort_dnascent_detect:
    cpus-per-task: 12
